apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
spec:
  accessModes: 
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/db-config
  capacity: 
    storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi